-- Cursos del Liceo Industrial Bicentenario de Electrotecnia RBL
SET NAMES utf8mb4;
insert into cursos (nombre, nivel) values
      ('1A', 'Media'),
      ('1B', 'Media'),
      ('1C', 'Media'),
      ('1D', 'Media'),
      ('1E', 'Media'),
      ('1F', 'Media'),
      ('2A', 'Media'),
      ('2B', 'Media'),
      ('2C', 'Media'),
      ('2D', 'Media'),
      ('2E', 'Media'),
      ('2F', 'Media'),
      ('3A', 'Electricidad'),
      ('3B', 'Electricidad'),
      ('3C', 'Electronica'),
      ('3D', 'Electronica'),
      ('3E', 'Telecomunicación'),
      ('3F', 'Telecomunicación'),
      ('3G', 'Programacion'),
      ('4A', 'Electricidad'),
      ('4B', 'Electricidad'),
      ('4C', 'Electronica'),
      ('4D', 'Electronica'),
      ('4E', 'Telecomunicación'),
      ('4F', 'Telecomunicación'),
      ('4G', 'Programacion');